fix 'nodejs::repo_ensure: absent' for yum
Presently, setting ensure to 'absent' results in creating two files in
/etc/yum.repos.d:

$ cat nodesource.repo
[nodesource]
$ cat nodesource-source.repo
[nodesource-source]

This results in yum failure:
$ sudo yum check-update
Loaded plugins: fastestmirror, security
Repository 'nodesource-source' is missing name in configuration, using id
Repository 'nodesource' is missing name in configuration, using id
Loading mirror speeds from cached hostfile
Error: Cannot find a valid baseurl for repo: nodesource

It is better to ensure these files do not exist. The corresponding apt
class is already set up this way.

Note: I was unable to get local tests working for this module, but I see
that there are automated tests; I will ensure they work.